# Generated by Django 6.0 on 2025-12-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
